version: "3.5"
services:
  api:
    build:
      context: ./app
      dockerfile: node.dockerfile
    restart: unless-stopped
    container_name: api
    ports:
      - "3000:3000"
    volumes:
      - ./app/node_modules:/usr/app/node_modules
      - ./app:/usr/app
    networks:
      api-network:
        aliases:
          - api

  test:
    build:
      context: ./test
      dockerfile: ruby.dockerfile
    volumes:
      - ./test:/usr/app
    environment:
      API_HOST: ${API_HOST}
      # CUCUMBER_PUBLISH_TOKEN: ${CUCUMBER_PUBLISH_TOKEN}
    external_links:
      - "api"
    networks:
      - api-network

networks:
  api-network:
